### ISSUE TITLE
where to find the "sero_mjmr_mcc_021918.tree" file?

### ISSUE THREAD

**Issue by liamxg** [taylorpaisie/visualization_scripts#2]
Dear @taylorpaisie,

Could I know where to find "sero_mjmr_mcc_021918.tree" file, thanks.

Best,
Liam

**Comment by taylorpaisie** [comment]
Sorry! i no longer have access to share that file.

**Comment by liamxg** [comment]
"Thank you for letting me know. If there's any alternative information you can provide or if there's another way we can proceed, please let me know. I appreciate your help!"

**Comment by taylorpaisie** [comment]
This tree was made with the program [BEAST](https://beast.community/).  By making a MCC tree with BEAST, you should be able to use the plot.

**Comment by liamxg** [comment]
Okay, got it, thanks.
